#!/bin/bash
# Open a cssh session to a given nodegroup in nventory
#
# Requires the nventory-client rubygem:
# $ gem install nventory-client
#
# Requires ~/.nventory.conf
# echo "server = http://nventory.corp.eharmony.com" > ~/.nventory.conf

FORCE_SYNC=0

while [[ $# -gt 1 ]]
do
	key="$1"

	case $key in
	    -u|--user)
	    LOGIN_USER="$2"
	    shift # past argument
	    ;;
	    --sync)
	    FORCE_SYNC=1
	    ;;
	    *)
		# unknown option
	    ;;
	esac
	shift # past argument or value
done


if [ 1 == $# ];
then
    NODE_GROUP="$1"
else
    echo "Must provide a node group"
    exit 1
fi

nodehosts=`nv --nodegroup $NODE_GROUP 2>/dev/null | grep eharmony.com | awk '{ print length, $0 }' | sort -n | cut -d" " -f2- | tr -d '\n'`

if [ `echo $nodehosts | wc -w` -eq 0 ]
then
	echo "Invalid nodegroup"
	exit -1
else
	if [ `grep -c $NODE_GROUP /Users/gpetroski/.zsh/completion/.sshn_nodegroups` -eq 0 ]
	then
		echo $NODE_GROUP >> /Users/gpetroski/.zsh/completion/.sshn_nodegroups
	fi
fi

echo "Connecting to: $nodehosts"

for host in $nodehosts
do
	sync-first $host $FORCE_SYNC
done

if [ `echo $nodehosts | wc -w` -eq 1 ]
then
	HOST=`echo $nodehosts | tr -d '[:space:]'`
	if [ -z "$LOGIN_USER" ]
	then
		ssh $HOST
	else
		ssh "${LOGIN_USER}@${HOST}"
	fi
else 
	if [ -z "$LOGIN_USER" ]
	then
		i2cssh -b $nodehosts
	else
		i2cssh -b $nodehosts -l $LOGIN_USER
	fi
fi
